### ISSUE TITLE
RegExp arguments are HTML content

### ISSUE THREAD

**Issue by freaktechnik** [Rantanen/eslint-plugin-xss#3]
Since I've updated babel-eslint, the `xss/no-mixed-html` rule triggers for the RegExp in
```js
...
const htmlPage = await data.text(),
            channelId = htmlPage.match(/<meta name="ustream:channel_id" content="([0-9]+)">/)[1];
...
```
with the warning test "HTML passed into function 'htmlPage.match'". `data` is a Response object from fetching a plain HTML page. I do not see how this would be a potential XSS issue and the error isn't exactly helpful either.

I'm disabling the rule for that line for now.

**Comment by Rantanen** [comment]
I guess a recent babel update has changed how regexes are represented in the AST.

Essentially the error is caused by Babel turning the `/<meta.../` regex object into something like a `new RegExp( "<meta name..." )` AST. The xss plugin has no built in consideration for the Regex constructor, so all it sees is a HTML fragment (which the "<meta name=..." looks like) being passed to a function that isn't declared safe for HTML.

At least that's my guess for now. I'll try to have a look at this in depth tomorrow and hopefully I'll come up with a fix. Whitelisting the `RegExp` constructor by default should be good enough.

**Comment by Rantanen** [comment]
(I haven't forgotten this - just didn't have much time during the end of the week or the weekend)

**Comment by Rantanen** [comment]
Okay, now I had forgotten this - or more specifically lost it. I did remember there was an open issue I meant to look at but I didn't remember which project of mine it was about... >_>

Taken care of now in any case! Better late than never I guess... :|

Turns out this was a problem with any regex, not just babel. Surprised I never encountered this before. I guess I've used `/stuff/.match( foo )` instead of `foo.match( /stuff/ )` myself.
